# Vignette-local scenarios of the NetworkOutbreaks vignettes (owner: WP34, V-NO).
#
# Every one is `derive`d from a registered NetworkEpiCore scenario, so it has its own canonical text and hash
# (design §E.4). Their summaries are committed next to the vignettes, in `vignettes/data/`, and are loaded with
# `scenario_summary(sc; dir = VIGNETTE_DATA)` (policy `:committed`: a missing or stale file is an error). They are
# regenerated by `vignettes/data/generate.jl`, with exactly the streams of `regenerate_scenarios`.
using NetworkEpiCore, NetworkOutbreaks, Catalyst

const VIGNETTE_DATA = normpath(joinpath(@__DIR__, "..", "data"))

# ---- 03: a vaccination pulse at t = 0 is a seeding of V ------------------------------------------------
# SIR with vaccination S → V at rate ν (the model of :sir_vax_pois5) with ν = 0 and 30% of all nodes in V
# at t = 0 (V is not infected, so it is not a seed of the epidemic).
const PULSE_FRACTION = 0.30
sirv_pulse0() = derive(scenario(:sir_vax_pois5); id = :sirv_pulse0_pois5,
    title = "SIR on Poisson(5) with 30% of the nodes vaccinated at t = 0",
    params = Dict(:ν => 0.0), initial = SeedFraction(:I => 0.01, :V => PULSE_FRACTION),
    notes = "NetworkOutbreaks vignette 03: the t = 0 vaccination pulse as a seeding of V.")

# ---- 04: neighbour-triggered quarantine S + I → Q + I -------------------------------------------------
const SIRQ = @reaction_network sirq begin
    @parameters τ α γ
    τ, S + I --> 2I          # infection: per-contact rate τ
    α, S + I --> Q + I       # quarantine of a susceptible by an infectious neighbour: per-contact rate α
    γ, I --> R
end
const TRACING_RATES = (0.05, 0.1, 0.2)
sirq_scenario(α) = derive(scenario(:sir_pois5); id = Symbol("sirq_pois5_a", replace(string(α), "." => "")),
    title = "SIR with neighbour-triggered quarantine (α = $(α)) on Poisson(5)",
    model = contact_model(SIRQ), params = Dict(:α => α),
    backends = Dict(:edge_based => :exact_limit), tags = [:vignette, :sir, :tracing, :configuration, :pt],
    expected = Symbol[],     # R₀ and T need the entry state of an infector: the registry does not compute them
    notes = "NetworkOutbreaks vignette 04: S + I → Q + I at the per-contact rate α.")

# ---- 05: the same scenario under every graph sampler ----------------------------------------------------
const ALGORITHM_VARIANTS = (:direct, :composition_rejection, :has)
algorithm_scenario(alg) = derive(scenario(:sir_pois5_N1000); id = Symbol("sir_pois5_N1000_", alg), algorithm = alg,
    title = "SIR on Poisson(5), N = 10³, 2000 runs, sampler :$(alg)",
    notes = "NetworkOutbreaks vignette 05: algorithm agreement against :sir_pois5_N1000 (NextReaction).")

# ---- 06: mass action on counts against the complete graph ----------------------------------------------
wm_small(alg) = derive(scenario(:sir_wm5); id = Symbol("sir_wm5_N500_", alg), N = 500, nsims = 1000, algorithm = alg,
    title = "SIR, well mixed (κ = 5), N = 500, 1000 runs, sampler :$(alg)",
    notes = "NetworkOutbreaks vignette 06: MassActionSSA against NextReaction on K_500 (lumping, M13).")

# ---- 02: the small-η dip of the DFD final size, at N = 10⁵ --------------------------------------------
# :sir_ne_reg6_eta1 (6-regular, τ = 1/12, γ = 1/4, 1% seeds) at η = 0.01 and on the static 6-regular network,
# with the same base seed, N = 10⁵ and 1000 runs each, so that a final-size difference of ≈ 0.004 is resolved.
const DIP_ETA = 0.01
const DIP_N = 100_000
function dfd_dip_scenario(which::Symbol)
    base = scenario(:sir_ne_reg6_eta1)
    net, id, what, tags = if which === :dynamic
        DynamicNetwork(RegularDegree(6), NeighbourExchange(DIP_ETA)), :sir_ne_reg6_eta001_N1e5,
        "neighbour exchange η = $(DIP_ETA)", vcat(base.tags, [:vignette])
    elseif which === :static
        ConfigurationNetwork(RegularDegree(6)), :sir_reg6_tau12_N1e5, "no exchange (static)",
        vcat(setdiff(base.tags, [:dynamic, :neighbour_exchange]), [:vignette, :configuration])
    else
        throw(ArgumentError("dfd_dip_scenario: `which` is :dynamic or :static, not :$(which)"))
    end
    return derive(base; id, network = net, backends = base.backends, tags,
        N = DIP_N, nsims = 1000, tspan = (0, 250),
        title = "SIR on a 6-regular network (τ = 1/12), $(what), N = 10⁵, 1000 runs",
        notes = "NetworkOutbreaks vignette 02: the final size at small η lies below the static value.")
end

vignette_scenarios() = Scenario[sirv_pulse0(); [sirq_scenario(a) for a in TRACING_RATES];
                                [algorithm_scenario(a) for a in ALGORITHM_VARIANTS];
                                wm_small(:mass_action); wm_small(:next_reaction);
                                dfd_dip_scenario(:dynamic); dfd_dip_scenario(:static)]
